flt q = 1.9382023;
bool isDeclared = false;
int x = 2;
int y = 3;
int p = 7;
int Q = 9;
int z = 0;
int t = 0;
int bb = 100;
int cc = 10000000;
str informalGreeting = "sup";
str formalGreeting = "hello";

function returnValidString() -> str {
	if (x equals 2){
		loop range(1,2){
			t = t + 1;
			log(isDeclared);
			log(informalGreeting);
		}
		ret(informalGreeting);
	}
	else {
		loop (x <= 10){
		   log(x);
		   x = x + 1;
		}
		ret(formalGreeting);
	}
}
call returnValidString();