flt q = 12.9382023;
flt r = 231231414.2;
bool isDeclared = false;
int x = 2;
int y = 3;
int p = 7;
int Q = 9;
int z = 0;
int t = 0;
int bb = 100;
int cc = 10000000;
str informalGreeting = "sup";
str formalGreeting = "hello";
int ARRAY numberList = {1,2,3,4,5,6,7,8,9,10};

function returnValidString() -> int {
    numberList.add(11); 
	if (x equals 2){
		loop range(1,2){
			t = t + 1;
			log(isDeclared);
			log(q);
		}
		ret(y);
	}
	else {
		loop (x <= 10){
		   log(x);
		   x = x + 1;
		}
		ret(x);
	}
}
call returnValidString();